package model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("login_log", "id", LoginLog.class);
		arp.addMapping("supplier_approve", "id", SupplierApprove.class);
		arp.addMapping("supplier_approve_record", "id", SupplierApproveRecord.class);
		arp.addMapping("suppliers_final", "id", SuppliersFinal.class);
		arp.addMapping("suppliers_temp", "id", SuppliersTemp.class);
		arp.addMapping("users", "id", Users.class);
	}
}

