package model;

import model.base.BaseLoginLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LoginLog extends BaseLoginLog<LoginLog> {
	public static final LoginLog dao = new LoginLog().dao();
}
