package model;

import model.base.BaseMenuRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MenuRole extends BaseMenuRole<MenuRole> {
	public static final MenuRole dao = new MenuRole().dao();
}
