package model;

import model.base.BaseSupplierApprove;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SupplierApprove extends BaseSupplierApprove<SupplierApprove> {
	public static final SupplierApprove dao = new SupplierApprove().dao();
}
