package model;

import model.base.BaseSuppliersFinal;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SuppliersFinal extends BaseSuppliersFinal<SuppliersFinal> {
	public static final SuppliersFinal dao = new SuppliersFinal().dao();
}
