package model;

import model.base.BaseSupplierApproveRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SupplierApproveRecord extends BaseSupplierApproveRecord<SupplierApproveRecord> {
	public static final SupplierApproveRecord dao = new SupplierApproveRecord().dao();
}
