package model;

import model.base.BaseSuppliersTemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SuppliersTemp extends BaseSuppliersTemp<SuppliersTemp> {
	public static final SuppliersTemp dao = new SuppliersTemp().dao();
}
