package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSupplierApproveRecord<M extends BaseSupplierApproveRecord<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setSupplierId(java.lang.String supplierId) {
		set("supplier_id", supplierId);
		return (M)this;
	}
	
	public java.lang.String getSupplierId() {
		return getStr("supplier_id");
	}

	public M setSupplierName(java.lang.String supplierName) {
		set("supplier_name", supplierName);
		return (M)this;
	}
	
	public java.lang.String getSupplierName() {
		return getStr("supplier_name");
	}

	public M setApprover(java.lang.String approver) {
		set("approver", approver);
		return (M)this;
	}
	
	public java.lang.String getApprover() {
		return getStr("approver");
	}

	public M setApproverStatus(java.lang.String approverStatus) {
		set("approver_status", approverStatus);
		return (M)this;
	}
	
	public java.lang.String getApproverStatus() {
		return getStr("approver_status");
	}

	public M setApproveJson(java.lang.String approveJson) {
		set("approve_json", approveJson);
		return (M)this;
	}
	
	public java.lang.String getApproveJson() {
		return getStr("approve_json");
	}

}
