package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLoginLog<M extends BaseLoginLog<M>> extends Model<M> implements IBean {

	public M setLoginid(java.lang.Long loginid) {
		set("loginid", loginid);
		return (M)this;
	}
	
	public java.lang.Long getLoginid() {
		return getLong("loginid");
	}

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setIp(java.lang.String ip) {
		set("ip", ip);
		return (M)this;
	}
	
	public java.lang.String getIp() {
		return getStr("ip");
	}

	public M setLogintime(java.util.Date logintime) {
		set("logintime", logintime);
		return (M)this;
	}
	
	public java.util.Date getLogintime() {
		return get("logintime");
	}

}
