package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSuppliersFinal<M extends BaseSuppliersFinal<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setSupplierName(java.lang.String supplierName) {
		set("supplier_name", supplierName);
		return (M)this;
	}
	
	public java.lang.String getSupplierName() {
		return getStr("supplier_name");
	}

	public M setSupplierCode(java.lang.Integer supplierCode) {
		set("supplier_code", supplierCode);
		return (M)this;
	}
	
	public java.lang.Integer getSupplierCode() {
		return getInt("supplier_code");
	}

	public M setContactNumber(java.lang.String contactNumber) {
		set("contact_number", contactNumber);
		return (M)this;
	}
	
	public java.lang.String getContactNumber() {
		return getStr("contact_number");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}

	public M setContactProvince(java.lang.String contactProvince) {
		set("contact_province", contactProvince);
		return (M)this;
	}
	
	public java.lang.String getContactProvince() {
		return getStr("contact_province");
	}

	public M setContactCity(java.lang.String contactCity) {
		set("contact_city", contactCity);
		return (M)this;
	}
	
	public java.lang.String getContactCity() {
		return getStr("contact_city");
	}

	public M setContactTown(java.lang.String contactTown) {
		set("contact_town", contactTown);
		return (M)this;
	}
	
	public java.lang.String getContactTown() {
		return getStr("contact_town");
	}

	public M setContactAddress(java.lang.String contactAddress) {
		set("contact_address", contactAddress);
		return (M)this;
	}
	
	public java.lang.String getContactAddress() {
		return getStr("contact_address");
	}

	public M setRegisteProvince(java.lang.String registeProvince) {
		set("registe_province", registeProvince);
		return (M)this;
	}
	
	public java.lang.String getRegisteProvince() {
		return getStr("registe_province");
	}

	public M setRegisteCity(java.lang.String registeCity) {
		set("registe_city", registeCity);
		return (M)this;
	}
	
	public java.lang.String getRegisteCity() {
		return getStr("registe_city");
	}

	public M setRegisteTown(java.lang.String registeTown) {
		set("registe_town", registeTown);
		return (M)this;
	}
	
	public java.lang.String getRegisteTown() {
		return getStr("registe_town");
	}

	public M setRegisteAddress(java.lang.String registeAddress) {
		set("registe_address", registeAddress);
		return (M)this;
	}
	
	public java.lang.String getRegisteAddress() {
		return getStr("registe_address");
	}

	public M setCfuscc(java.lang.String cfuscc) {
		set("cfuscc", cfuscc);
		return (M)this;
	}
	
	public java.lang.String getCfuscc() {
		return getStr("cfuscc");
	}

	public M setLegalEntity(java.lang.String legalEntity) {
		set("legal_entity", legalEntity);
		return (M)this;
	}
	
	public java.lang.String getLegalEntity() {
		return getStr("legal_entity");
	}

	public M setPhoneNumber(java.lang.String phoneNumber) {
		set("phone_number", phoneNumber);
		return (M)this;
	}
	
	public java.lang.String getPhoneNumber() {
		return getStr("phone_number");
	}

	public M setIdNumber(java.lang.String idNumber) {
		set("id_number", idNumber);
		return (M)this;
	}
	
	public java.lang.String getIdNumber() {
		return getStr("id_number");
	}

	public M setBusinessScope(java.lang.String businessScope) {
		set("business_scope", businessScope);
		return (M)this;
	}
	
	public java.lang.String getBusinessScope() {
		return getStr("business_scope");
	}

	public M setBussinessLicence(java.lang.String bussinessLicence) {
		set("bussiness_licence", bussinessLicence);
		return (M)this;
	}
	
	public java.lang.String getBussinessLicence() {
		return getStr("bussiness_licence");
	}

	public M setBussinessBylaw(java.lang.String bussinessBylaw) {
		set("bussiness_bylaw", bussinessBylaw);
		return (M)this;
	}
	
	public java.lang.String getBussinessBylaw() {
		return getStr("bussiness_bylaw");
	}

}
